/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/actions` | `/actions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forum` | `/forum`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homes` | `/homes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quick-action` | `/quick-action`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/society` | `/society`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/actions` | `/actions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/forum` | `/forum`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/homes` | `/homes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/quick-action` | `/quick-action`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/services` | `/services`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/society` | `/society`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/actions${`?${string}` | `#${string}` | ''}` | `/actions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/forum${`?${string}` | `#${string}` | ''}` | `/forum${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/homes${`?${string}` | `#${string}` | ''}` | `/homes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/quick-action${`?${string}` | `#${string}` | ''}` | `/quick-action${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/services${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/society${`?${string}` | `#${string}` | ''}` | `/society${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/actions` | `/actions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forum` | `/forum`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homes` | `/homes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quick-action` | `/quick-action`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/society` | `/society`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
